# greetd configuration
# See: https://man.archlinux.org/man/greetd.5

[terminal]
# The VT to run the greeter on
vt = 1

[default_session]
command = "start-hyprland -- -c /etc/greetd/hyprland.conf"
user = "greeter"
